AllCops:
  TargetRubyVersion: 2.3.4
  DisplayCopNames: true
  Exclude:
    - 'config/puma.rb'
    - 'db/**/*.rb'
  Rails:
    Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/DateTime:
  Enabled: false
