language: ruby
rvm:
  - 2.3.4
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
bundler_args:
  --without production
  --binstubs=./bundler_stubs
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
services:
  - postgresql
