development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('PGDATABASE', 'made_assistant_development') %>
  pool: 10
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PGPORT', '5432') %>
  username: <%= ENV.fetch('PGUSER', 'made_assistant') %>
  password: <%= ENV.fetch('PGPASSWORD', '') %>

test:
  <<: *default
  database: made_assistant_test
  min_messages: error

production:
  <<: *default
  database: made_assistant_production
  username: made_assistant
  password: <%= ENV['MADE_ASSISTANT_DATABASE_PASSWORD'] %>
